services:
    # Service Manager
    papis.media_manager:
        class: Puzzle\Api\MediaBundle\Service\MediaManager
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $errorFactory: '@papis.error_factory'
    
    papis.media_uploader:
        class: Puzzle\Api\MediaBundle\Service\MediaUploader
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $mediaManager: '@papis.media_manager'
            $maxSize: '%puzzle_api_media.max_size%'
    
    # Listeners
    papis.event_listener.media:
        class:  Puzzle\Api\MediaBundle\Listener\MediaListener
        arguments: [ '@doctrine.orm.entity_manager', '@papis.media_manager', '@papis.media_uploader' ]
        tags:
            - { name: kernel.event_listener, event: papis.media.create_folder, method: onCreateFolder }
            - { name: kernel.event_listener, event: papis.media.rename_folder, method: onRenameFolder }
            - { name: kernel.event_listener, event: papis.media.remove_folder, method: onRemoveFolder }
            - { name: kernel.event_listener, event: papis.media.add_files_to_folder, method: onAddFilesToFolder }
            - { name: kernel.event_listener, event: papis.media.remove_files_to_folder, method: onRemoveFilesToFolder }
            - { name: kernel.event_listener, event: papis.media.create_file, method: onCreateFile }
            - { name: kernel.event_listener, event: papis.media.copy_file, method: onCopyFile }
            - { name: kernel.event_listener, event: papis.media.rename_file, method: onRenameFile }
            - { name: kernel.event_listener, event: papis.media.remove_file, method: onRemoveFile }
    
